### ISSUE TITLE
Where is the AutoDraw.sketchplugin file?

### ISSUE THREAD

**Issue by rivera-irving** [sympli/autodraw-sketch#3]
This is no file called AutoDraw.sketchplugin on this repo

<img width="1050" alt="autodraw-sketch-master" src="https://cloud.githubusercontent.com/assets/10568768/25057687/a378b416-2137-11e7-9944-9776e81b9a2b.png">

**Comment by mxxnsk** [comment]
It seems like you downloaded zipped repository w/ source code. 

[Here is a link to release](https://github.com/sympli/autodraw-sketch/releases/download/1.0/AutoDraw.sketchplugin.zip)
